allowBuilds:
  "@tailwindcss/oxide": true
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - astro-icon@1.2.0
  - '@jsr/ivyrose__feed@0.1.1'
onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
