name: deploy site
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v6
              with:
                  version: 10

            - name: get deps
              run: pnpm install

            - name: licensed fa-pro icons
              run: rsync -a ~/fa-pro-icons/ src/icons/fa-pro/

            - name: build site
              run: pnpm build

            - name: deploy
              run: rsync -av --delete ./dist/ /opt/sites/ivy.rs/
